# Generated by Django 2.2.11 on 2020-08-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflame', '0002_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='avtar/'),
        ),
    ]
