# Generated by Django 2.2.11 on 2020-08-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflame', '0003_course_avtar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
