# Generated by Django 2.2.11 on 2020-08-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0002_color_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_avialable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('is_avialable', models.BooleanField(default=True)),
                ('colors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_task.Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_task.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
